# Generated by Django 5.1 on 2024-08-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='m2_terreno',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='numero_est',
            field=models.IntegerField(default=0),
        ),
    ]
