# Generated by Django 5.1 on 2024-08-15 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0002_inmuebles_m2_terreno_inmuebles_numero_est'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='correo',
        ),
        migrations.AlterField(
            model_name='profile',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_tipo_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='m7_python.tipo_user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rut',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.CharField(max_length=100),
        ),
    ]
