# Generated by Django 5.1 on 2024-08-23 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0003_remove_profile_correo_alter_profile_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=64)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
    ]
